apiVersion: v2
description: A Helm chart cert-manager ACME Webhook for INWX
name: cert-manager-webhook-inwx
version: 0.0.1
appVersion: v0.0.1
maintainers:
  - name: realzollsoft
    url: https://github.com/realzollsoft/cert-manager-webhook-inwx
