name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Test Jobs
  lint-helm:
    uses: ./.github/workflows/.lint-charts.yml

  lint-and-test-go:
    uses: ./.github/workflows/.lint-and-test-go.yml
    secrets: inherit